### ISSUE TITLE
unable to load

### ISSUE THREAD

**Issue by Aileilaya** [maoxs2/AutoACM#1]
Lifecycle scripts included in autoacm:
  test
    echo "Error: no test specified" && exit 1
on windows 10 npm 3.10.10

**Comment by c0mm4nd** [comment]
It is my fault on README.

The message tells you that in `npm run`( the way to execute npm in npm script which was pre-written in package.json file) you can use the `test` (means the `npm run test`) command to deal with sth.

But in `test` command, I didn't retain anything, except the default string `echo "Error: no test specified" && exit 1`. So you see it.

As you see, I havent commit any code to this repo for a long time. So it is also unfinished as a PROJECT. But it is a useful SCRIPT which did lots of problems for me before.

Finally I recommend that you can use the oldest commit of repo and study more on nodejs programming.( I will also fix the intro and take a try on dev)

**Comment by Aileilaya** [comment]
Thx a lot
